version: '3'
services:
  prf-form:
    container_name: prf-form
    restart: always
    build: .
    ports:
      - '4000:4000'
    # expose:
    #   - 80
    restart: always
#     volumes: ['./:/var/www/html']
    environment:
      VIRTUAL_HOST: passwords.cbtseminary.com, www.passwords.cbtseminary.com
      LETSENCRYPT_HOST: passwords.cbtseminary.com, www.passwords.cbtseminary.com
      LETSENCRYPT_EMAIL: course.info@cbtseminary.org
networks:
  default:
    external:
      name: nginx-proxy